demo_app/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/hierarchy/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root to: 'jobs#new'
  resources :jobs, only: [:new, :create]
end

demo_app/app/models/bad_worker.rb
class BadWorker
  include Sidekiq::Worker

  sidekiq_options retry: false

  def perform(*args)
    raise 'nope'
  end
end

demo_app/app/models/child_worker.rb
class ChildWorker
  include Sidekiq::Worker

  def perform(*args)
    if rand(2) == 0
      TestWorker.perform_async(*args)
    else
      BadWorker.perform_async(*args)
    end
  end
end

demo_app/app/models/failing_worker.rb
class FailingWorker
  include Sidekiq::Worker

  def perform(*args)
    raise 'nope' unless rand(2) == 1
  end
end

demo_app/app/models/parent_worker.rb
class ParentWorker
  include Sidekiq::Worker

  sidekiq_options queue: :high

  def perform(*args)
    5.times do |n|
      TestWorker.perform_async(n)
    end
  end
end

demo_app/app/models/test_worker.rb
class TestWorker
  include Sidekiq::Worker

  SAMPLE = [0, 0, 1, 5]

  sidekiq_options workflow: true, workflow_keys: ['args']

  def perform(*args)
    sleep 2
    SAMPLE.sample.times do |n|
      TestWorker.perform_async(n)
    end
  end
end

demo_app/app/models/web_worker.rb
require 'sidekiq/hierarchy/faraday/middleware'

class WebWorker
  include Sidekiq::Worker

  ROOT_PATH = 'http://localhost:3000'

  sidekiq_options workflow: true, queue: :ultralow

  def perform(*args)
    conn = Faraday.new(url: ROOT_PATH) do |f|
      f.request :url_encoded
      f.use Sidekiq::Hierarchy::Faraday::Middleware
      f.adapter Faraday.default_adapter
    end

    conn.post '/jobs', worker: ParentWorker.name
  end
end

demo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demo_app/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
  end

  def create
    if params[:worker].blank?
      flash[:error] = 'No worker type selected'
    else
      jid = params[:worker].constantize.perform_async
      flash[:success] = "Kicked off a workflow with jid #{jid}"
    end

    redirect_to new_job_path
  end
end

demo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

demo_app/app/views/jobs/new.erb
<span><%= flash[:success] %></span>
<span><%= flash[:error] %></span>

<%= form_tag jobs_path do %>
  <div>
    <%= radio_button_tag :worker, TestWorker.name %>
    <%= label_tag "worker_#{TestWorker.name}", TestWorker.name %>
    <%= radio_button_tag :worker, WebWorker.name %>
    <%= label_tag "worker_#{WebWorker.name}", WebWorker.name %>
    <%= radio_button_tag :worker, ParentWorker.name %>
    <%= label_tag "worker_#{ParentWorker.name}", ParentWorker.name %>
  </div>

  <%= submit_tag 'Make me a job', data: {confirm: "As fast as I can?"} %>
<% end %>

demo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>